### ISSUE TITLE
fatal error after post or page update or publish

### ISSUE THREAD

**Issue by ikyamoet** [maximeschoeni/sublanguage#29]
Hello, 
When updating or publishing another language than the original I got a blank page returning to this url : https://xxxxxx.com/wp-admin/post.php

Debug tell me this : 

`Fatal error: Uncaught Error: [] operator not supported for strings in /home/xxxxxxxxxx/public_html/wp-content/plugins/sublanguage/class-admin.php:823 Stack trace: #0 /home/xxxxxxxxxx/public_html/wp-includes/class-wp-hook.php(286): Sublanguage_admin->terms_clauses(Array, Array, Array) #1 /home/xxxxxxxxxx/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 /home/xxxxxxxxxx/public_html/wp-includes/class-wp-term-query.php(647): apply_filters('terms_clauses', Array, Array, Array) #3 /home/xxxxxxxxxx/public_html/wp-includes/class-wp-term-query.php(288): WP_Term_Query->get_terms() #4 /home/xxxxxxxxxx/public_html/wp-includes/taxonomy.php(1099): WP_Term_Query->query(Array) #5 /home/xxxxxxxxxx/public_html/wp-admin/includes/post.php(356): get_terms(Array, Array) #6 /home/xxxxxxxxxx/public_html/wp-admin/post.php(194): edit_post() #7 {main} thrown in /home/xxxxxxxxxx/public_html/wp-content/plugins/sublanguage/class-admin.php on line 823`

Can you help maybe?
Thanks

**Comment by maximeschoeni** [comment]
Hello,

Sounds like a string is passed in a some get_terms query as meta_query parameter (instead of an array).

I added a few line to prevent an error within Sublanguage when this happens. I just made a commit, please have a try.

**Comment by ikyamoet** [comment]
Perfect! All works well now, thanks a lot!!
Wonderful little plugin! 
Best,
Simon
